name: Validate Vocabulary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install rdflib pyyaml pytest
    
    - name: Validate vocabulary
      run: python tools/validate.py
    
    - name: Run tests
      run: pytest tests/
